[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.streamlit"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PORT = "8501"
